version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1884:1884"    # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - default
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"      # HTTP voor test zonder SSL
      - "443:443"      # HTTPS
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs   # Voeg de certificaten toe
    networks:
      - default

networks:
  default:
    driver: bridge
