version: '3.8'

services:
  web:
    build: .
    container_name: my-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["node", "server.js"]
